import { AppError,normalizeNoteBody,normalizeNoteTitle,noteContainsUnsafeMarkup,type CreateStudentNoteInput,type NoteContextReference,type StudentNote,type UpdateStudentNoteInput } from "@tlp/shared-types";
import { createUserScopedSupabaseClient } from "./supabase";
const NOTE_SELECT="id,title,body,created_at,updated_at";
const dep=(message:string)=>new AppError({code:"DEPENDENCY_UNAVAILABLE",message,retryable:true});
function validateBody(body:string){if(noteContainsUnsafeMarkup(body))throw new AppError({code:"VALIDATION_ERROR",message:"Note content contains unsafe active markup",retryable:false});}
function validContexts(items:NoteContextReference[]){const allowed=new Set(["learning_path","course","module","mission","competency","lab_definition","lab_session","content_asset"]);return items.map(c=>{const stableId=String(c.stableId??"").trim();if(!allowed.has(c.contextType)||!stableId)throw new AppError({code:"VALIDATION_ERROR",message:"Invalid note context reference",retryable:false});return {...c,stableId};});}
async function contextsFor(token:string,noteId:string):Promise<NoteContextReference[]>{const s=createUserScopedSupabaseClient(token);const {data,error}=await s.from("student_note_contexts").select("context_type,context_stable_id,context_version").eq("note_id",noteId).order("created_at",{ascending:true});if(error)throw dep("Unable to load note context");return (data??[]).map(r=>({contextType:String(r.context_type) as NoteContextReference["contextType"],stableId:String(r.context_stable_id),...(r.context_version==null?{}:{version:Number(r.context_version)})}));}
function map(row:Record<string,unknown>,contexts:NoteContextReference[]):StudentNote{return{id:String(row.id),title:String(row.title??""),body:String(row.body??""),contexts,createdAt:String(row.created_at),updatedAt:String(row.updated_at)};}
async function replaceContexts(token:string,noteId:string,items:NoteContextReference[]){const s=createUserScopedSupabaseClient(token);const {error:d}=await s.from("student_note_contexts").delete().eq("note_id",noteId);if(d)throw dep("Unable to update note context");if(!items.length)return;const {error}=await s.from("student_note_contexts").insert(items.map(c=>({note_id:noteId,context_type:c.contextType,context_stable_id:c.stableId,context_version:c.version??null})));if(error)throw dep("Unable to update note context");}
export async function listStudentNotes(token:string){const s=createUserScopedSupabaseClient(token);const {data,error}=await s.from("student_notes").select(NOTE_SELECT).order("updated_at",{ascending:false});if(error)throw dep("Unable to load notes");return Promise.all((data??[]).map(async r=>map(r as Record<string,unknown>,await contextsFor(token,String(r.id)))));}
export async function getStudentNote(token:string,id:string){const s=createUserScopedSupabaseClient(token);const {data,error}=await s.from("student_notes").select(NOTE_SELECT).eq("id",id).maybeSingle();if(error)throw dep("Unable to load note");if(!data)throw new AppError({code:"NOT_FOUND",message:"Note not found",retryable:false});return map(data as Record<string,unknown>,await contextsFor(token,id));}
export async function createStudentNote(token:string,input:CreateStudentNoteInput){let title:string,body:string;try{title=normalizeNoteTitle(input.title);body=normalizeNoteBody(input.body);}catch(e){throw new AppError({code:"VALIDATION_ERROR",message:e instanceof Error?e.message:"Invalid note",retryable:false});}validateBody(body);const contexts=validContexts(input.contexts??[]);const s=createUserScopedSupabaseClient(token);const {data,error}=await s.from("student_notes").insert({title,body}).select(NOTE_SELECT).single();if(error||!data)throw dep("Unable to create note");await replaceContexts(token,String(data.id),contexts);return map(data as Record<string,unknown>,contexts);}
export async function updateStudentNote(token:string,id:string,input:UpdateStudentNoteInput){const patch:Record<string,unknown>={};try{if(input.title!==undefined)patch.title=normalizeNoteTitle(input.title);if(input.body!==undefined)patch.body=normalizeNoteBody(input.body);}catch(e){throw new AppError({code:"VALIDATION_ERROR",message:e instanceof Error?e.message:"Invalid note",retryable:false});}if(typeof patch.body==="string")validateBody(patch.body);const s=createUserScopedSupabaseClient(token);const {data,error}=await s.from("student_notes").update(patch).eq("id",id).select("id").maybeSingle();if(error)throw dep("Unable to save note");if(!data)throw new AppError({code:"NOT_FOUND",message:"Note not found",retryable:false});if(input.contexts!==undefined)await replaceContexts(token,id,validContexts(input.contexts));return getStudentNote(token,id);}
export async function deleteStudentNote(token:string,id:string){const s=createUserScopedSupabaseClient(token);const {data,error}=await s.from("student_notes").delete().eq("id",id).select("id").maybeSingle();if(error)throw dep("Unable to delete note");if(!data)throw new AppError({code:"NOT_FOUND",message:"Note not found",retryable:false});}
